# Generated by Django 2.2.1 on 2020-01-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtype',
            name='type_images',
            field=models.FileField(upload_to='article/blog_images/'),
        ),
    ]
