# Generated by Django 2.2.1 on 2020-01-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200122_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtype',
            name='type_images',
            field=models.ImageField(upload_to='article/blog_images/'),
        ),
    ]
