# Generated by Django 2.2.1 on 2020-01-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200128_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
